recipe: default.v1
language: "pt"

pipeline:
  - name: "WhitespaceTokenizer"
  - name: "CountVectorsFeaturizer"
  - name: "DIETClassifier"
    epochs: 100
    constrain_similarities: True
  - name: "EntitySynonymMapper"
  - name: "ResponseSelector"
    epochs: 100

policies:
  - name: "MemoizationPolicy"
  - name: "TEDPolicy"
    max_history: 5
    epochs: 100
  - name: "RulePolicy"
